// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpMezFDjsA0rtTU-UdzCQv7c0x6-n9Uw',
    appId: '1:101172943999:web:a5cd22c805deb03a8eb34a',
    messagingSenderId: '101172943999',
    projectId: 'local-link-63f75',
    authDomain: 'local-link-63f75.firebaseapp.com',
    storageBucket: 'local-link-63f75.firebasestorage.app',
    measurementId: 'G-5JPHMQGD42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpkbeajrAwYbw1Z1itIOyNhEGdokbAbdY',
    appId: '1:101172943999:android:dbe4cb8589b1157d8eb34a',
    messagingSenderId: '101172943999',
    projectId: 'local-link-63f75',
    storageBucket: 'local-link-63f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlvPw6kIPV56gvJo3YhiPvCenCsv1ScG8',
    appId: '1:101172943999:ios:24471e248855d8e08eb34a',
    messagingSenderId: '101172943999',
    projectId: 'local-link-63f75',
    storageBucket: 'local-link-63f75.firebasestorage.app',
    iosBundleId: 'com.example.localLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlvPw6kIPV56gvJo3YhiPvCenCsv1ScG8',
    appId: '1:101172943999:ios:24471e248855d8e08eb34a',
    messagingSenderId: '101172943999',
    projectId: 'local-link-63f75',
    storageBucket: 'local-link-63f75.firebasestorage.app',
    iosBundleId: 'com.example.localLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhpMezFDjsA0rtTU-UdzCQv7c0x6-n9Uw',
    appId: '1:101172943999:web:b28732875541cea18eb34a',
    messagingSenderId: '101172943999',
    projectId: 'local-link-63f75',
    authDomain: 'local-link-63f75.firebaseapp.com',
    storageBucket: 'local-link-63f75.firebasestorage.app',
    measurementId: 'G-2EGJFYF2GV',
  );
}
